services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # 백엔드
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./AI:/app/AI
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "how-much-geo-test.vercel.app:216.198.79.67"
    dns:
      - 8.8.8.8
      - 8.8.4.4
      
  # 프론트엔드
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_VWORLD_WFS_URL=/vworld-api/req/wfs
      - CHOKIDAR_USEPOLLING=true
    dns:
      - 8.8.8.8
      - 1.1.1.1
    depends_on:
      - backend

volumes:
  redis_data: