services:

  # 데이터베이스
  db:
    image: mirror.gcr.io/library/postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  # 레디스
  redis:
    image: mirror.gcr.io/library/redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # 백엔드
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./AI:/app/AI
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "how-much-geo-test.vercel.app:216.198.79.67"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - db
      - redis
      
  # 프론트엔드
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_VWORLD_WFS_URL=/vworld-api/req/wfs
      - CHOKIDAR_USEPOLLING=true
    dns:
      - 8.8.8.8
      - 1.1.1.1
    depends_on:
      - backend

volumes:
  pg_data:
  redis_data: